export default [
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 1,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 2,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 3,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 4,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 5,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 6,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 7,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 8,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 8,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 9,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 12,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 11,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 13,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 14,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 15,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 9,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 15,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 16,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 17,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 0,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },

  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 1,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 2,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 3,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 4,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 5,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 6,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 7,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 8,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 8,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 9,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 12,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 11,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 13,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 14,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 15,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 9,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 15,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 16,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 17,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 0,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
  {
    name: 'Aboleth',
    challengeRating: 10,
    description: 'Large aberration, lawful evil',
    image: 'https://media-waterdeep.cursecdn.com/avatars/thumbnails/0/11/1000/1000/636238825975375671.jpeg',
    hitPoints: 140,
    ac: 16,
    speed: 40,
    actions: [
      {
        name: 'Tail',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (3d6 + 5) bludgeoning damage.',
      }, {
        name: 'Tentacle',
        type: 'Melee Weapon Attack',
        description: '+9 to hit, reach 10 ft., one target. Hit: (2d6 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 14 Constitution saving throw or become diseased.',
      },
    ],
    savingThrows: {
      dex: 7,
      con: 15,
      wis: 10,
      cha: 12,
    },
  },
];
